name: Unit tests

on:
  push:

jobs:
  common:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        node-version: [20.x]  # Updated Node version to meet Lerna 8+ requirements

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npx lerna run build

      - name: Run tests
        run: npx lerna run test
        env:
          CI: true